### ISSUE TITLE
add the frame for database server

### ISSUE THREAD

**Issue by leducthai** [leducthai/Archive#1]
@quocbang I will do this tomorrow

**Comment by quocbang** [comment]
> @quocbang I will do this tomorrow

@leducthai  do you have a plan for this week?

**Comment by quocbang** [comment]
@leducthai  please create some toto, project stacks,...

**Comment by leducthai** [comment]
I have finished the frame

**Comment by leducthai** [comment]
> @leducthai please create some toto, project stacks,...

can you clarify what you do mean "some toto"
